#!/bin/bash

read -p "backup volume name          : " backup_drive
read -p "directory to back up [$HOME]: " backup_dir
conf="$HOME/.bk-conf"

if [ -z "$backup_dir" ]; then
    backup_dir="$HOME"
fi

echo "# Configuration file for automated backups." >> $conf
echo "" >> $conf
echo "backup_drive=\"$backup_drive\"" >> $conf
echo "backup_dir=\"$HOME\"" >> $conf
echo "backup_log=\"$HOME/.bk.log\"" >> $conf

echo "config file created: $HOME/.bk-conf"
echo "contents:"
cat "$conf" | sed "s/^/    /"

