#!/bin/bash

bin=`dirname $0`
. "$bin/bk-lib.sh"

read -p "backup volume name          : " backup_drive
read -p "directory to back up [$HOME]: " backup_dir
conf="$HOME/.bk-conf"

if [ -z "$backup_dir" ]; then
    backup_dir="$HOME"
fi

log "# Configuration file for automated backups." >> $conf
log "" >> $conf
log "backup_drive=\"$backup_drive\"" >> $conf
log "backup_dir=\"$HOME\"" >> $conf
log "backup_log=\"$HOME/.bk.log\"" >> $conf

log "config file created: $HOME/.bk-conf"
log "contents:"
cat "$conf" | sed "s/^/    /"

log "checking auto-mount status of $backup_drive"
$bin/bk-statecheck
