#!/bin/bash


bin=`dirname $0`
. "$HOME/.bk-conf"
. "$bin/bk-lib.sh"

log "backup drive: $backup_drive"
log "log file    : $backup_log"

bk-mount "$backup_drive"

log "TODO: update backup"

bk-unmount "$backup_drive"

