#!/bin/bash

if [ -z "$1" ]; then
    echo "usage: $0 <volume name>"
    exit 10
fi

function count_volumes {
    num_volumes=`diskutil list | grep -i "$1" | wc -l`
    echo $num_volumes
}

function get_volume_id {
    volume_id=`diskutil list | grep -i "$1" | sed -n -e 's/^.* //p'`
    echo $volume_id
}

volume_name="$1"
echo "(re)mounting $1"
num_volumes=`count_volumes "$volume_name"`
echo "found $num_volumes volumes matching '$volume_name'"
case $num_volumes in
    0)
        echo "exiting"
        exit 11
        ;;
    1)
        volume_id=`get_volume_id "$volume_name"`
        echo "mounting: $volume_id"
        diskutil mount "$volume_id" | sed "s/^/    /"
        exit $?
        ;;
    *)
        echo "NOT mounting any drives"
        echo "exiting"
        exit 11
        ;;
esac
    
