#!/bin/bash


bin=`dirname $0`
. "$HOME/.bk-conf"
. "$bin/bk-lib.sh"

title "BACKING UP TO $backup_drive"

log "backup drive: $backup_drive"
log "log file    : $backup_log"

bk-mount "$backup_drive"

backup_files

bk-unmount "$backup_drive"

log "done"

